name: Pages

on:
  - push
  - pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Install Nikola
      run: |
        pip install webassets
        pip install -U --upgrade-strategy=eager Nikola==8.0.0b2
    - name: Build site
      run: nikola build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        cname: savingjournalism.reprozip.org
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
